### ISSUE TITLE
 BlockNetLogicException: DialogUnexpected "stake distribution for epoch #179 is unknown"

### ISSUE THREAD

**Issue by shuhuan2014** [input-output-hk/cardano-sl#4276] opened 2020-03-09 11:53 UTC
```
[cardano-sl.*production*:Debug:ThreadId 830] [2020-03-09 11:51:15.97 UTC] ### **Rolling: run applyAMAP: apply as much as possible after `verifyBlocksPrefix` failure: ApplyBlocksVerifyFailure (VerifyBlocksError "stake distribution for epoch #179 is unknown")**
[cardano-sl.*production*:Info:ThreadId 830] [2020-03-09 11:51:15.97 UTC] slogVerifyBlocks: Consensus era is OBFT ObftLenient
[cardano-sl.*production*:Debug:ThreadId 830] [2020-03-09 11:51:15.97 UTC] usVerifyBlocks OBFT: We're on epoch boundary. Running processGenesisBlock
[cardano-sl.*production*:Info:ThreadId 830] [2020-03-09 11:51:15.97 UTC] Verifying and applying blocks done
[cardano-sl.*production*:Debug:ThreadId 830] [2020-03-09 11:51:15.97 UTC] MemPool metrics release: ApplyBlock modify time was 1600099mcs size is 0
[cardano-sl.*production*:Warning:ThreadId 830] [2020-03-09 11:51:15.97 UTC] Failed to verify blocks: stake distribution for epoch #179 is unknown
  blocks = [6013a2cd635edf77, b73b4947cadb44f8, 13330b44fbdd7b4f, a57568f6c33c1709, 3298839a235a740e, 35f01836892969c1, 9a078195a84f78b1, adc79afdc30abbb6, fa37d9d49a3e7658, cb8fb623997899e9, 342cd269fcab1d17, 8c7bf24b10e2fa72, 1801d54cd1726738, 9b817fd022e26f95, 25436948d72a4d3e, 21a966dcabc788e0, c8546ed98e560057, 24b477fa6a4b215b, 15d4c088f874ce48, f0794d772af895e6, 783dd812941038bf, efd4c67b593aca89, 6fc0c106490b116a, da9be47abe8aa6b9, 86da624d4e1185a5, c2468849734998e3, 6c5936ae539e7ab9, 2548d5bc24fb18d4, 5281229ba6bc03dc, f65244933a0d6629, fe9686d9271d34a9, 63c33189cb962fc4, de6f03601199cab4, 3dd88a969830f210, e1159a6d95cc4c1f, 697a056b0a93cd2d, 19e57aca7776a945, 28d66414906bf906, 2191a183aa57f66d, 7b634b23b42af92e, e31980ce88ccd6b1, 40f493b64ec6e14c, 342b103014948461, 22e9bf1aacb53d58, 1bda40707e58b1fc, e0bc086815e9113c, f612a3876f03021c, 82c1af08a84be59b, 4581edb9bfee006f, 291677f67587b2ad, 461e20b4a6cefb63, 6dd6c1c4bc19e29f, 785e7b5836395ab6, d2b9aef60dde4f5b, 767f615fb0c38b9f, 2c2ae3611a8936b1, 037c0ba4f7f72157, 9381cd97b011563f, 00ecb4ef583ada89, 08b59eb2bb66e306, a607b9b860a9933b, a9ebe009bf2e627f, e52169235f0871a3, 7e8d2c632bbade67]
[cardano-sl.diffusion.outboundqueue.self:Warning:ThreadId 824] [2020-03-09 11:51:15.99 UTC] sending MsgRequestBlocks (fromList [NodeId 13.228.156.8:3000:0]) to NodeId 13.228.156.8:3000:0 failed with BlockNetLogicException: DialogUnexpected "stake distribution for epoch #179 is unknown" :: SomeException
[cardano-sl.*production*:Warning:ThreadId 360] [2020-03-09 11:51:15.99 UTC] handleRecoveryE: error handling nodeId="13.228.156.8:3000:0", header=a21fb3e98b6337a3: BlockNetLogicException: DialogUnexpected "stake distribution for epoch #179 is unknown"
[cardano-sl.*production*:Warning:ThreadId 360] [2020-03-09 11:51:15.99 UTC] Recovery mode communication dropped with peer "13.228.156.8:3000:0"
[cardano-sl.*production*:Debug:ThreadId 360] [2020-03-09 11:51:15.99 UTC] Attempting to restart recovery
[cardano-sl.*production*:Info:ThreadId 362] [2020-03-09 11:51:16.58 UTC] Triggering recovery because we need it
[cardano-sl.*production*:Debug:ThreadId 362] [2020-03-09 11:51:16.58 UTC] Recovery triggered, requesting tips from neighbors
```
What version is this? Is it a release version or something compiled from Git? If the latter, please supply the git hash.

**Comment by erikd** [comment] 2020-03-12 03:59
Closing this as a dupe of #4277 .

**Closed as completed by erikd** 2020-03-12 03:59 UTC
